
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace EF.UI.Views {
    using System;
    using Terminal.Gui;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Drawing;
    
    
    public partial class MainView : Terminal.Gui.Window {
        
        private Terminal.Gui.TabView dataTabView;
        
        private Terminal.Gui.ListView personListView;
        
        private Terminal.Gui.ListView employmentListView;
        
        private Terminal.Gui.Window infoWindow;
        
        private Terminal.Gui.TextView infoTextView;
        
        private Terminal.Gui.Window optionsWindow;
        
        private Terminal.Gui.Button addFakeDataButton;
        
        private Terminal.Gui.Button updateButton;
        
        private Terminal.Gui.Button deleteButton;
        
        private Terminal.Gui.Button addPersonButton;
        
        private Terminal.Gui.Button querieButton;
        
        private Terminal.Gui.Button addEmploymentButton;
        
        private void InitializeComponent() {
            this.addEmploymentButton = new Terminal.Gui.Button();
            this.querieButton = new Terminal.Gui.Button();
            this.addPersonButton = new Terminal.Gui.Button();
            this.deleteButton = new Terminal.Gui.Button();
            this.updateButton = new Terminal.Gui.Button();
            this.addFakeDataButton = new Terminal.Gui.Button();
            this.optionsWindow = new Terminal.Gui.Window();
            this.infoTextView = new Terminal.Gui.TextView();
            this.infoWindow = new Terminal.Gui.Window();
            this.employmentListView = new Terminal.Gui.ListView();
            this.personListView = new Terminal.Gui.ListView();
            this.dataTabView = new Terminal.Gui.TabView();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = Pos.Center();
            this.Y = Pos.Center();
            this.Visible = true;
            this.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.Modal = false;
            this.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Title = "EF - Aplikacja przechowywyjąca informacje o osobach";
            this.dataTabView.Width = Dim.Percent(45);
            this.dataTabView.Height = Dim.Fill(0);
            this.dataTabView.X = 0;
            this.dataTabView.Y = 0;
            this.dataTabView.Visible = true;
            this.dataTabView.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.dataTabView.Data = "dataTabView";
            this.dataTabView.TextAlignment = Terminal.Gui.Alignment.Start;
            this.dataTabView.MaxTabTextWidth = 30u;
            this.dataTabView.Style.ShowBorder = true;
            this.dataTabView.Style.ShowTopLine = true;
            this.dataTabView.Style.TabsOnBottom = false;
            Terminal.Gui.Tab dataTabViewpeople;
            dataTabViewpeople = new Terminal.Gui.Tab();
            dataTabViewpeople.DisplayText = "People";
            dataTabViewpeople.View = new View();
            dataTabViewpeople.View.Width = Dim.Fill();
            dataTabViewpeople.View.Height = Dim.Fill();
            this.personListView.Width = Dim.Percent(100);
            this.personListView.Height = Dim.Percent(100);
            this.personListView.X = Pos.Center();
            this.personListView.Y = Pos.Center();
            this.personListView.Visible = true;
            this.personListView.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.personListView.Data = "personListView";
            this.personListView.TextAlignment = Terminal.Gui.Alignment.Start;
            this.personListView.Source = new Terminal.Gui.ListWrapper<string>(new System.Collections.ObjectModel.ObservableCollection<string>(new string[] {
                            "Item1",
                            "Item2",
                            "Item3"}));
            this.personListView.AllowsMarking = false;
            this.personListView.AllowsMultipleSelection = true;
            dataTabViewpeople.View.Add(this.personListView);
            dataTabView.AddTab(dataTabViewpeople, false);
            Terminal.Gui.Tab dataTabViewemployments;
            dataTabViewemployments = new Terminal.Gui.Tab();
            dataTabViewemployments.DisplayText = "Employments";
            dataTabViewemployments.View = new View();
            dataTabViewemployments.View.Width = Dim.Fill();
            dataTabViewemployments.View.Height = Dim.Fill();
            this.employmentListView.Width = Dim.Percent(100);
            this.employmentListView.Height = Dim.Percent(100);
            this.employmentListView.X = Pos.Center();
            this.employmentListView.Y = Pos.Center();
            this.employmentListView.Visible = true;
            this.employmentListView.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.employmentListView.Data = "employmentListView";
            this.employmentListView.TextAlignment = Terminal.Gui.Alignment.Start;
            this.employmentListView.Source = new Terminal.Gui.ListWrapper<string>(new System.Collections.ObjectModel.ObservableCollection<string>(new string[] {
                            "Item1",
                            "Item2",
                            "Item3"}));
            this.employmentListView.AllowsMarking = false;
            this.employmentListView.AllowsMultipleSelection = true;
            dataTabViewemployments.View.Add(this.employmentListView);
            dataTabView.AddTab(dataTabViewemployments, false);
            this.dataTabView.ApplyStyleChanges();
            this.Add(this.dataTabView);
            this.infoWindow.Width = Dim.Percent(55);
            this.infoWindow.Height = Dim.Percent(73);
            this.infoWindow.X = Pos.Right(dataTabView);
            this.infoWindow.Y = Pos.Top(dataTabView);
            this.infoWindow.Visible = true;
            this.infoWindow.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.infoWindow.Modal = false;
            this.infoWindow.Data = "infoWindow";
            this.infoWindow.TextAlignment = Terminal.Gui.Alignment.Start;
            this.infoWindow.Title = "Details";
            this.Add(this.infoWindow);
            this.infoTextView.Width = Dim.Percent(100);
            this.infoTextView.Height = Dim.Percent(100);
            this.infoTextView.X = Pos.Center();
            this.infoTextView.Y = Pos.Center();
            this.infoTextView.Visible = true;
            this.infoTextView.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.infoTextView.AllowsTab = true;
            this.infoTextView.AllowsReturn = true;
            this.infoTextView.WordWrap = false;
            this.infoTextView.Data = "infoTextView";
            this.infoTextView.Text = "";
            this.infoTextView.TextAlignment = Terminal.Gui.Alignment.Start;
            this.infoWindow.Add(this.infoTextView);
            this.optionsWindow.Width = Dim.Percent(55);
            this.optionsWindow.Height = Dim.Fill(0);
            this.optionsWindow.X = Pos.Right(dataTabView);
            this.optionsWindow.Y = Pos.Bottom(infoWindow);
            this.optionsWindow.Visible = true;
            this.optionsWindow.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.optionsWindow.Modal = false;
            this.optionsWindow.Data = "optionsWindow";
            this.optionsWindow.TextAlignment = Terminal.Gui.Alignment.Start;
            this.optionsWindow.Title = "Options";
            this.Add(this.optionsWindow);
            this.addFakeDataButton.Width = Dim.Auto();
            this.addFakeDataButton.Height = 1;
            this.addFakeDataButton.X = Pos.Center() - 20;
            this.addFakeDataButton.Y = Pos.Center() - 1;
            this.addFakeDataButton.Visible = true;
            this.addFakeDataButton.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.addFakeDataButton.Data = "addFakeDataButton";
            this.addFakeDataButton.Text = "Add Fake Data";
            this.addFakeDataButton.TextAlignment = Terminal.Gui.Alignment.Center;
            this.addFakeDataButton.IsDefault = false;
            this.optionsWindow.Add(this.addFakeDataButton);
            this.updateButton.Width = Dim.Auto();
            this.updateButton.Height = 1;
            this.updateButton.X = Pos.Center();
            this.updateButton.Y = Pos.Center() - 1;
            this.updateButton.Visible = true;
            this.updateButton.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.updateButton.Data = "updateButton";
            this.updateButton.Text = "Update";
            this.updateButton.TextAlignment = Terminal.Gui.Alignment.Center;
            this.updateButton.IsDefault = false;
            this.optionsWindow.Add(this.updateButton);
            this.deleteButton.Width = Dim.Auto();
            this.deleteButton.Height = 1;
            this.deleteButton.X = Pos.Center() + 20;
            this.deleteButton.Y = Pos.Center() - 1;
            this.deleteButton.Visible = true;
            this.deleteButton.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.deleteButton.Data = "deleteButton";
            this.deleteButton.Text = "Delete";
            this.deleteButton.TextAlignment = Terminal.Gui.Alignment.Center;
            this.deleteButton.IsDefault = false;
            this.optionsWindow.Add(this.deleteButton);
            this.addPersonButton.Width = Dim.Auto();
            this.addPersonButton.Height = 1;
            this.addPersonButton.X = Pos.Center() - 20;
            this.addPersonButton.Y = Pos.Center() + 2;
            this.addPersonButton.Visible = true;
            this.addPersonButton.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.addPersonButton.Data = "addPersonButton";
            this.addPersonButton.Text = "Add Person";
            this.addPersonButton.TextAlignment = Terminal.Gui.Alignment.Center;
            this.addPersonButton.IsDefault = false;
            this.optionsWindow.Add(this.addPersonButton);
            this.querieButton.Width = Dim.Auto();
            this.querieButton.Height = 1;
            this.querieButton.X = Pos.Center();
            this.querieButton.Y = Pos.Center() + 2;
            this.querieButton.Visible = true;
            this.querieButton.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.querieButton.Data = "querieButton";
            this.querieButton.Text = "Queries";
            this.querieButton.TextAlignment = Terminal.Gui.Alignment.Center;
            this.querieButton.IsDefault = false;
            this.optionsWindow.Add(this.querieButton);
            this.addEmploymentButton.Width = Dim.Auto();
            this.addEmploymentButton.Height = 1;
            this.addEmploymentButton.X = Pos.Center() + 20;
            this.addEmploymentButton.Y = Pos.Center() + 2;
            this.addEmploymentButton.Visible = true;
            this.addEmploymentButton.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.addEmploymentButton.Data = "addEmploymentButton";
            this.addEmploymentButton.Text = "Add Employmenta";
            this.addEmploymentButton.TextAlignment = Terminal.Gui.Alignment.Center;
            this.addEmploymentButton.IsDefault = false;
            this.optionsWindow.Add(this.addEmploymentButton);
        }
    }
}
