
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace EF.UI.Views {
    using System;
    using Terminal.Gui;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Drawing;
    
    
    public partial class SelectorView : Terminal.Gui.Window {
        
        private Terminal.Gui.ListView selectorListView;
        
        private void InitializeComponent() {
            this.selectorListView = new Terminal.Gui.ListView();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.Arrangement = (Terminal.Gui.ViewArrangement.Movable | Terminal.Gui.ViewArrangement.Overlapped);
            this.Modal = false;
            this.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Title = "";
            this.selectorListView.Width = Dim.Percent(40);
            this.selectorListView.Height = Dim.Fill(0);
            this.selectorListView.X = Pos.Center();
            this.selectorListView.Y = Pos.Center();
            this.selectorListView.Visible = true;
            this.selectorListView.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.selectorListView.Data = "selectorListView";
            this.selectorListView.TextAlignment = Terminal.Gui.Alignment.Start;
            this.selectorListView.Source = new Terminal.Gui.ListWrapper<string>(new System.Collections.ObjectModel.ObservableCollection<string>(new string[] {
                            "Item1",
                            "Item2",
                            "Item3"}));
            this.selectorListView.AllowsMarking = false;
            this.selectorListView.AllowsMultipleSelection = true;
            this.Add(this.selectorListView);
        }
    }
}
